stages:
  - prepare
  - test
image: python:3.11
variables:
  POSTGRES_DB: mydb
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  DECODE_JWT_TOKEN: token

  VITE_GOOGLE_API_KEY: AIzaSyD0WOz5-uNYkUA3rp7V1iAm6U5Ro_-3vmI
  VITE_SECRET_KEY: 12345678901234567890123456789012
  VITE_IV: 1234567890123456

  GITLAB_PIPELINE: 'true'

be_dependencies:
  stage: prepare
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - git clone https://$CI_GENERIC_TEST_USERNAME:$CI_GENERIC_TEST_TOKEN@gitlab.com/generic-lab/generics/generic-test.git
    - cd generic-test
    - pip install -r ./requirements.txt
  artifacts:
    paths:
      - generic-test
      - venv
    expire_in: 1h
  tags:
    - linux

test_end_to_end:
  stage: test
  needs:
    - job: be_dependencies
      artifacts: true
  services:
    - name: postgres:15
      alias: postgres
    - name: selenium/standalone-chromium:latest
      alias: selenium
  script:
    - apt-get update && apt-get install -y npm
    - npm ci
    - npm run build
    - npm run serve &

    - cd ../generic-test
    - pytest -s ./tests/italco/ ./tests/generic-module
  artifacts:
    when: always
    paths:
      - generic-test/screenshots/
    expire_in: 1 week
  tags:
    - linux

lint_frontend:
  stage: test
  image: node:18
  script:
    - npm ci
    - npx eslint "src/**/*.{js,vue}"
  tags:
    - linux
