FROM node:20

WORKDIR /app

ARG VITE_HOSTNAME_GENERIC_BE_PROD
ARG CARPEDIEM_VITE_FORM_MAIL
ARG CARPEDIEM_VITE_GA_TRACKING_ID
ARG CARPEDIEM_PORT_PROD

ENV VITE_HOSTNAME=$VITE_HOSTNAME_GENERIC_BE_PROD
ENV VITE_FORM_MAIL=$CARPEDIEM_VITE_FORM_MAIL
ENV VITE_GA_TRACKING_ID=$CARPEDIEM_VITE_GA_TRACKING_ID
ENV PORT=$CARPEDIEM_PORT_PROD
ENV PORT=3000

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build:app

CMD ["npm", "run", "serve"]
