FROM node:20

WORKDIR /app

ARG VITE_HOSTNAME
ARG VITE_FORM_MAIL
ARG VITE_GA_TRACKING_ID
ARG VITE_DISABLE_ANALYTICS

ENV VITE_HOSTNAME=$VITE_HOSTNAME
ENV VITE_FORM_MAIL=$VITE_FORM_MAIL
ENV VITE_GA_TRACKING_ID=$VITE_GA_TRACKING_ID
ENV VITE_DISABLE_ANALYTICS=$VITE_DISABLE_ANALYTICS

ENV PORT=3000

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build:app

CMD ["npm", "run", "serve"]
