FROM node:20

WORKDIR /app

ARG VITE_HOSTNAME
ARG VITE_DISABLE_ANALYTICS
ARG CARPEDIEM_VITE_FORM_MAIL
ARG CARPEDIEM_VITE_GA_TRACKING_ID

ENV VITE_HOSTNAME=$VITE_HOSTNAME
ENV VITE_FORM_MAIL=$CARPEDIEM_VITE_FORM_MAIL
ENV VITE_DISABLE_ANALYTICS=$VITE_DISABLE_ANALYTICS
ENV VITE_GA_TRACKING_ID=$CARPEDIEM_VITE_GA_TRACKING_ID
ENV PORT=3000

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build:app

CMD ["npm", "run", "serve"]
