export { default as Map } from '@/components/sections/Map.vue'
export { default as Line } from '@/components/sections/Line.vue'
export { default as Gallery } from '@/components/sections/Gallery.vue'
export { default as Services } from '@/components/sections/Services.vue'
export { default as Contacts } from '@/components/sections/Contacts.vue'
export { default as BrandList } from '@/components/sections/BrandList.vue'
export { default as Advantages } from '@/components/sections/Advantages.vue'
export { default as DualSection } from '@/components/sections/DualSection.vue'

export { useMobileUtils } from '@/utils/mobile'
export { useLanguageStore } from '@/stores/language'
